### ISSUE TITLE
Does not work on files with multiple periods.

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [ajitsing/apkToJava#5]
For example, "android.example.apk" will ALWAYS fail unless it is renamed, regardless of if it actually has a .dex file in it.

**Comment by TheElementalOfDestruction** [comment]
Also note that the program does not like files with parenthesis.

**Comment by ajitsing** [comment]
@TheElementalOfCreation Thanks for reporting the bug, I will fix it ASAP.

**Comment by ajitsing** [comment]
@TheElementalOfCreation fixed the issue in https://github.com/ajitsing/apkToJava/releases/tag/1.3.1
